name: Build Windows install wim

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: '构建版本号'
        required: true
        default: '10.0.19043.1'
      lang:
        description: '语言ID'
        required: true
        default: 'zh-CN'


jobs:
  run-command:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '8.0.x'
      - name: Download UUPs
        shell: pwsh
        env:
          BUILD_NUMBER: ${{ github.event.inputs.build_number }}
        run: |
          .\UUPDownload.exe -s Professional -r Retail -b Retail -c vb_release -l ${{ github.event.inputs.lang }} -v $env:BUILD_NUMBER -y -t amd64 -o .\dl
      - name: check and move
        shell: pwsh
        run: |
          ls dl
          Get-ChildItem -Path "dl" -Recurse -File | Move-Item -Destination "converter\UUPs" -Force
      - name: Build wim
        shell: cmd
        run: |
          cd converter
          dir UUPs
          echo 0 | call convert-UUP.cmd
      - name: pack
        shell: cmd
        run: |
          cd converter
          ..\7zr a -v1900m ..\install.wim.7z install.wim
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          # 显式传递 Token（可以使用默认的 GITHUB_TOKEN，也可以是自定义 PAT）
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "${{ github.event.inputs.build_number }}_${{ github.event.inputs.lang }}"
          # 显式指定 Release 的显示标题
          name: "${{ github.event.inputs.build_number }}_${{ github.event.inputs.lang }}"
          files: |
            .\install.wim.7*
